name: 'Setup Splitgraph client'
description: 'Set up the sgr CLI to manipulate datasets / jobs on remote Splitgraph instances, for example, triggering data loads, dbt projects etc.'
inputs:
  splitgraph_deployment_url:
    description: "URL to the Splitgraph deployment. Defaults to splitgraph.com."
    default: "splitgraph.com"
    required: false
  splitgraph_api_key:
    description: "Splitgraph API key. Will log into Splitgraph if specified. You can generate a key pair at https://www.splitgraph.com/settings/sql-credentials (use your deployment domain instead of splitgraph.com on private deployments)."
    required: false
  splitgraph_api_secret:
    description: "Splitgraph API secret."
    required: false
  sgr_version:
    description: "Version of sgr to download, e.g. 0.3.0"
    default: "latest"
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        ${{ github.action_path }}/setup_splitgraph.sh ${{ inputs.splitgraph_deployment_url }} ${{ inputs.splitgraph_api_key }} ${{ inputs.splitgraph_api_secret }}
      shell: bash
      env:
        SGR_VERSION: ${{ inputs.sgr_version }}
